### ISSUE TITLE
Move forms from `api/forms.py` to the `accounts/forms.py`

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1028]
## Idea summary

There are several account/profile forms defined in [`api/forms.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/forms.py). Those forms should be moved to [`accounts/forms.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/forms.py) or deleted if they are duplicate code.

**Update:** the code in `api/forms.py` is actually redundant, so may simply be deleted.

## Task

The steps to complete this task are:

- [x] [fork this repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and clone it to your local computer
- [x] set up a local development environment as [outlined in our Contributing Guide](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/CONTRIBUTING.md#development)
- [x] delete the file `api/forms.py`
- [x] commit your changes
- [x] push your code to GitHub
- [x] [open a pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) against the `main` branch in this repository

**Comment by anurag629** [comment]
I want to contribute and resolve this issue. 
Please guide me in this how I proceed to fix bug

**Comment by brylie** [comment]
Thanks, @anurag629  ! I'll assign you.

I've added steps to complete this issue in the description above, under the "Task" section.

I'm not sure of your familiarity with all of those steps, so I may have included steps that are obvious. In any case, feel free to ask for assistance with any questions or ideas.

**Comment by anurag629** [comment]
after cloning, I have to delete the file named 'forms.py'  OpenCiviWiki\project\api\forms.py.
Kindly check the path.

Thank You!

**Comment by brylie** [comment]
Go shead and commit your changes and open a pull request. That way it will be easier for me to review.
