### ISSUE TITLE
Create `categories` app with initial code

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1040]
Both the `accounts` and `threads` apps use categories, in order to link accounts with relevant threads. As categories are a common dependency, we should move category-related code to a separate app.

## Task
- [ ] Create a new `categories` app. Move related code from the `api` app to `categories`.

### Further details

Steps to complete this task:

- [ ] create a `categories` app
	- `python manage.py startapp categories`
- [ ] add the `categories` app under `INSTALLED_APPS` in [`core/settings.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/core/settings.py#L19)
- [ ] move category-related code from the `api` to the `categories` app
    - [ ] [`api/models/category.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/category.py) -> `categories/models.py`
    - [ ] remove [api/__init__.py Category import](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/models/__init__.py#L5)
    - [ ] [`api/views/category.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/views/category.py) -> `categories/api.py`
    - [ ] category serializers from [`api/serializers.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/serializers.py#L193) -> `categories/serializers.py`
        - [ ] [`CategoryListSerializer`](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/serializers.py#L193)
        - [ ] [`CategorySerializer`](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/serializers.py#L200)
- [ ] Commit your changes and push to GitHub
- [ ] Open a pull request for assistance

## Assistance
Once the pull request is open, we can assist with the following steps
- [ ] fix `Category` imports in `accounts` and `threads` app (where possible) 
- [ ] create database migration(s)
    - [ ] `python manage.py makemigrations`
    - [ ] `python manage.py migrate`
- [ ] Commit changes, push to GitHub, and open a pull request against the `main` branch in this repository

**Comment by AbhijithGanesh** [comment]
if there is no one to volunteer, I am always up Brylie @brylie

**Comment by anurag629** [comment]
I will make PR after completing steps

**Comment by anurag629** [comment]
sir, I did with the initial steps but at step(fix Category imports in accounts and threads app (where possible)) I am a little bit confused because I don't have knowledge about serializers. 
I know what is serializer but don't know how its connections work.

Please help to make PR.

**Comment by brylie** [comment]
For this task, just focus on moving the code to the new locations and deleting it from the old locations as outlined in the issue description. 

Once you have moved the code, push your changes to GitHub and open a pull request so that we can help out with any import or migration issues.

**Comment by brylie** [comment]
@anurag629 I went ahead and divided the checklist above into two halves.

- moving the files (then pushing to GitHub and opening a pull request)
- fixing imports and adding migrations (the parts we can assist with)

Would you mind working through the first half of the checklist by

1. locating each specific file linked in the description
2. moving each specific code (e.g., function or class) linked in the checklist item to its new location
3. deleting each specific code from the original location

Once each specific code item (function or class) has been moved to its new location, commit the changes, push to GitHub, and open a pull request. 

We can assist with any difficulties you encounter related to git/GitHub if you let us know what is blocking your progress.

**Comment by anurag629** [comment]
Ok, Thank you, sir.
I will make PR after completing the steps.

**Comment by wassafshahzad** [comment]
@brylie  Can I look into this as well?

**Comment by AbhijithGanesh** [comment]
When are we rolling out v2.0 @brylie ?

**Comment by brylie** [comment]
> When are we rolling out v2.0

Please [start a new discussion](https://github.com/CiviWiki/OpenCiviWiki/discussions) with these types of questions, so that issue discussions can remain focused.

**Comment by brylie** [comment]
Assigning to @anurag629 since they have already opened a pull request.
