### ISSUE TITLE
Restore and improve fixtures in `project/data/`

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1079]
Our project contains some [fixture data](https://docs.djangoproject.com/en/3.2/howto/initial-data/#providing-data-with-fixtures) that is useful to quickly populate our Categories and Threads models. However, we don't tell developers how to use the fixtures or that they even exist.

## Task

- [x] determine how to use fixtures to populate our initial data
- [x] test our existing fixtures to make sure they still work
  - [x] if needed, improve the fixture data so it works with any model changes 
- [x] #1081

## Original issue

<details>

<summary>original issue opened by @AbhijithGanesh</summary>

### Idea summary

Using one standard form of data 

### Further details

Currently we use both constants.py and .json to store common data rather than using both since it leads to confusion
```js
[{
    "fields": {
        "name": "Agriculture"
    },
    "model": "api.category",
    "pk": 0
},{
    "fields": {
        "name": "Environment"
    },
    "model": "api.category",
    "pk": 1
}, {
    "fields": {
        "name": "Energy"
    },
    "model": "api.category",
    "pk": 2
}, {
 ...
{
    "fields": {
        "name": "Other"
    },
    "model": "api.category",
    "pk": 21
}]

``` 
and you can view constants here
[Constants](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/core/constants.py)

</details>

**Comment by AbhijithGanesh** [comment]
@brylie do we use the data from data directory anymore?

**Comment by brylie** [comment]
The constants are used in Python code, so should remain as .py. Whereas the `.json` file is used to populate the Categories table with default categories, in the example above.

In both cases, I believe we are following established conventions.

Related documentation:

- Django docs - Providing initial data for models: [Providing data with fixtures](https://docs.djangoproject.com/en/3.2/howto/initial-data/#providing-data-with-fixtures)

**Comment by brylie** [comment]
> do we use the data from data directory anymore?

I believe we can use this issue to improve our documentation. I.e. we can add a sub-section to our development guide describing how to use the `categories.json` and `sample_threads.json`.

**Comment by AbhijithGanesh** [comment]
Got it, then I think the .json file should not reference api right?
We need to reference them to newer models right? @brylie

**Comment by AbhijithGanesh** [comment]
can I work on this?

**Comment by brylie** [comment]
> Got it, then I think the .json file should not reference api right?

@AbhijithGanesh, yes good catch! 

> can I work on this?
Yes please. I'll assign you and update the issue description accordingly with a task list.

**Comment by AbhijithGanesh** [comment]
@brylie I have created a new issue for documentation and have left it open for new contributors, if there aren't volunteers, I shall volunteer to contribute😄

**Comment by SachinHatikankar100** [comment]
Hi, @AbhijithGanesh I am unable to find the documentation. Can you please help me to locate it? Not sure if I can contribute but wanted to have a look at it.

**Comment by AbhijithGanesh** [comment]
No we need someone to create it @SachinHatikankar100 . Someone has to write the docs for how to use fixtures in django
Read the docs related to fixtures [here](https://docs.djangoproject.com/en/3.2/howto/initial-data/)
We need this to be updated on our contributing.md
You can view the documentation issue here: #1081

**Comment by LightFelicis** [comment]
Hi, I'll gladly take this issue if it's free :)

**Comment by AbhijithGanesh** [comment]
Can you please request on #1081 @LightFelicis
