### ISSUE TITLE
Change Thread.author FK to point to the `User` model instead of `Profile`

### ISSUE THREAD

**Issue by gorkemarslan** [CiviWiki/OpenCiviWiki#1097]
Our `Thread.author` field is currently a foreign-key relationship to the `Profile` model. However, user profiles are to some extent optional. Furthermore, the lack of default Profile object for each user has led to some uncertainty in our database fixture data.

## Task

- [ ] change the `Thread.author` model to be an FK relationship to the `User` table
- [ ] make sure related views, templates, and other functions still work as expected
- [ ] if needed, add model properties to make it easy to fech a `user.profile` and `thread.author_profile`

## Original issue

Issues #1079 and #1081 are about loading initial data to the project.

```json
    {
        "model": "threads.Thread",
        "fields": {
            "title": "Liquid Fluoride Thorium Reactors",
            "summary": "...",
            "category_id": "2",
            "author_id": "1",
            "created": "2016-10-09 21:07:16.848433+00"
        }
    },
```

and

```
python manage.py loaddata ./data/categories.json
python manage.py loaddata ./data/sample_threads.json
```

According to them, there should be at least a profile instance on the database. It is assumed to be `superuser`. 

But the `superuser` does not have any profile. So running the command below:

`python manage.py createsuperuser`

creates a user instance:

```
>>> from django.contrib.auth import get_user_model
>>> get_user_model().objects.count()
>>> 1
```

but not creates a profile:

```
>>> from accounts.models import Profile
>>> Profile.objects.count()
>>> 0
```

So in the `OpenCiviWiki`, no registered profile has superuser privileges unless given from `admin` panel. 

@brylie, if this situation is not an intended decision in the project, I want to override `createsuperuser` so that

`python manage.py createsuperuser`

creates a profile.

**Comment by brylie** [comment]
I believe our `Thread` model should be updated to reference a `User` ID rather than `Profile`.

**Comment by gorkemarslan** [comment]
`Thread` model now:

```python
class Thread(models.Model):
    author = models.ForeignKey(
        Profile, default=None, null=True, on_delete=models.PROTECT
    )
    ....
```

So Thread `model` should be updated such that

```python
class Thread(models.Model):
    author = models.ForeignKey(
        get_user_model(), default=None, null=True, on_delete=models.PROTECT
    )
    ....
```

**Comment by brylie** [comment]
Jep, that looks good.

**Comment by brylie** [comment]
It might take some re-wiring of the "create thread" form and code path. I'm not sure to what extent that change would need to propagate through the code. E.g. in templates, we might need to change the context to something like `thread.author.profile` and check whether the profile exists for safety. Let's just make the minimum changes necessary to make the DB migration work without errors. We can enhance templates later as we start porting things from Backbone to pure Django templates.

**Comment by gorkemarslan** [comment]
If you want we can adjust `Profile` model as `AUTH_USER_MODEL`, if refactoring will be really a big deal.

Or we can update `Profile` model such that:
**Before:**
```python
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=63, blank=False)
    last_name = models.CharField(max_length=63, blank=False)
    about_me = models.CharField(max_length=511, blank=True)
```

**After:**
```python
class Profile(AbstractUser):
    first_name = models.CharField(max_length=63, blank=False)
    last_name = models.CharField(max_length=63, blank=False)
    about_me = models.CharField(max_length=511, blank=True)
```

Either way, we'll have minimal code changes.

Edit: I am not sure whether the first one will work. `AUTH_USER_MODEL` might need a user model inherited from `AbstractBaseUser`.

**Comment by gorkemarslan** [comment]
@brylie, then why do we have the `Profile` model in the project if we use the `User` model? 😅

**Comment by brylie** [comment]
The `Profile` model contains additional information about users that is not required to log in. I.e., the `User` model has what is essential to log in, and the `Profile` should contain *optional* information such as name and biography.

**Comment by gorkemarslan** [comment]
I now understand their differences. So `Profile` model is here to validate optional data.

**Comment by gorkemarslan** [comment]
We should refactor all `threads/models.py`:

https://github.com/CiviWiki/OpenCiviWiki/blob/9bc01dd3b4d492ef1cb2a7f1d5f1a27535f1ae48/project/threads/models.py#L442-L445

https://github.com/CiviWiki/OpenCiviWiki/blob/9bc01dd3b4d492ef1cb2a7f1d5f1a27535f1ae48/project/threads/models.py#L475-L478

https://github.com/CiviWiki/OpenCiviWiki/blob/9bc01dd3b4d492ef1cb2a7f1d5f1a27535f1ae48/project/threads/models.py#L387-L390

https://github.com/CiviWiki/OpenCiviWiki/blob/9bc01dd3b4d492ef1cb2a7f1d5f1a27535f1ae48/project/threads/models.py#L203-L207

One additional note:
To use `user.profile` we need to change

```python
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
```

to

```python
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="profile")
```

Otherwise, reverse relation is called with `user.profile_set`. I also add `related_name` arguments for simplicity.

**Comment by gorkemarslan** [comment]
@brylie, I have a question:

Why does the `Profile` model have a many-to-one relation with the `User` model?

https://github.com/CiviWiki/OpenCiviWiki/blob/9bc01dd3b4d492ef1cb2a7f1d5f1a27535f1ae48/project/accounts/models.py#L93-L94

We could use `one-to-one` [relation](https://docs.djangoproject.com/en/3.2/ref/models/fields/#onetoonefield).

Did I miss a point? Because now a user can have multiple profiles but a profile has only one user.

**Comment by brylie** [comment]
> We could use one-to-one relation.

Yes, each user should have exactly one Profile, at most. And, a Profile pertains to only one user. So, one-to-one relationship sounds right.

**Comment by gorkemarslan** [comment]
@brylie, what about `serializers`?
https://github.com/CiviWiki/OpenCiviWiki/blob/3de9e1eb30765d665770c3d56fbd3c4143d30eb6/project/threads/serializers.py#L115-L117

Are we going to update `accounts/serializers.py`? ([accounts/serializers.py](https://github.com/CiviWiki/OpenCiviWiki/blob/3de9e1eb30765d665770c3d56fbd3c4143d30eb6/project/accounts/serializers.py))

**Comment by brylie** [comment]
Yes, we would need to update any code that currently relies on `Profile` to switch it to using `User`. For now, we can just display the `User.username` field instead of any particular fields of `Profile` model, to make this transition easier.

**Comment by gorkemarslan** [comment]
Then I should create `UserListSerializer` to be replaced with `ProfileListSerializer` such that:

```python
 class ThreadSerializer(serializers.ModelSerializer): 
     """ """ 
     author = UserListSerializer(required=False) 
```


```python
class UserListSerializer(UserCommonSerializer):
    """
    Serializer for multiple user model instances
    """
    class Meta:
        model = User
        fields = ("username",)
```

We can add other fields if you want. Which one do you prefer?:

```python
class UserListSerializer(UserCommonSerializer):
    """
    Serializer for multiple user model instances
    """

    first_name = serializers.ReadOnlyField()
    last_name = serializers.ReadOnlyField()

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
        )
```

**Comment by brylie** [comment]
Very detailed findings so far!
