### ISSUE TITLE
Make `linked_civis` and `response_civis` fields optional on Civi model

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1101]
The `Civi` model contains two required fields that are causing difficulty when starting a fresh project:

- `linked_civis` https://github.com/CiviWiki/OpenCiviWiki/blob/85cd5bf867be4e1987cff3f083fc456904287f9e/project/threads/models.py#L214
- `response_civis` https://github.com/CiviWiki/OpenCiviWiki/blob/85cd5bf867be4e1987cff3f083fc456904287f9e/project/threads/models.py#L215-L221

Since those fields are required, it is not possible to create the first Civi, due to the "chicken and egg" situation where no Civis exist.

## Task

- [x] remove the `response_civis` field
- [x] make the `linked_civis` field optional
- [x] create database migrations with `python manage.py makemigrations`

## Original report
@AbhijithGanesh opened this issue originally with the following information.

### Description

Without fixtures in Civi, it is not possible to create Civis and it is requires a civi to be referenced when created, which makes it impossible to create.

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, could you share the error messages you encounter and also how you get them?

**Comment by AbhijithGanesh** [comment]
I was unable to get the model instances via the views therefore I registered the models through Admin and tried creating a civi and it returns me the following:
![image](https://user-images.githubusercontent.com/67182544/136074477-7172f60b-1f21-4911-a976-a133b5dba3eb.png)

This is circularly routed.

**Comment by brylie** [comment]
@AbhijithGanesh, I have repurposed this bug report to make the `linked_civis` field optional and remove the `response_civis` field.

**Comment by AbhijithGanesh** [comment]
@gorkemarslan and @brylie I wasn't working on this over the weekend, will do this today

**Comment by AbhijithGanesh** [comment]
Brylie check this
https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/threads/models.py

**Comment by brylie** [comment]
We may also need `null=True` here:

https://github.com/CiviWiki/OpenCiviWiki/blob/364b9b1fe85b7610b25d97454342d9c80f5bdb0f/project/threads/models.py#L219

**Comment by brylie** [comment]
Do we also have the database migration?

**Comment by AbhijithGanesh** [comment]
I will check and let ya know

**Comment by AbhijithGanesh** [comment]
> `null=True`

Null has no effect on ManyToManyField according to django
You can view them [here](https://docs.djangoproject.com/en/3.2/ref/models/fields/#ManyToManyField)

**Comment by AbhijithGanesh** [comment]
![image](https://user-images.githubusercontent.com/67182544/136978840-cb752927-7244-43f9-ad9c-9affb634d379.png)

For your reference @brylie

**Comment by brylie** [comment]
OK, the `null=True` was not needed. However, we do need a database migration for these changes. Please consider deleting the previously generated database migration, removing the `null=True`, and re-generating the database migration for this pull request.
