### ISSUE TITLE
Remove code related to U.S. state and government structure

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1106]
We are trying to simplify the CiviWiki codebase while making it more relevant to communities outside of the United States. To that end, we have removed most code related to the U.S. legislature and bills. However, some specific code remains that isn't relevant to people in other countries.

## Task

- [ ] Remove U.S.-centric code from the project
- [ ] create database migrations with `python manage.py makemigrations`

## Specific code to remove

- [ ] Remove `level_CHOICES`, `level`, and `state`: https://github.com/CiviWiki/OpenCiviWiki/blob/3de9e1eb30765d665770c3d56fbd3c4143d30eb6/project/threads/models.py#L90-L95

- [ ] Remove `US_STATES` imports: 
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/3de9e1eb30765d665770c3d56fbd3c4143d30eb6/project/threads/models.py#L9
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/b15b942e21531e2252726ee6d0e37425be6977fa/project/frontend_views/views.py#L13
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L23

- [ ]  Remove `US_STATES` constant: https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/core/constants.py#L13-L66

- [ ]  Remove "state" and "level" code from Thread model manager: https://github.com/CiviWiki/OpenCiviWiki/blob/85cd5bf867be4e1987cff3f083fc456904287f9e/project/threads/models.py#L47-L49

- [ ]  Remove states-related code from API views:
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/b15b942e21531e2252726ee6d0e37425be6977fa/project/frontend_views/views.py#L46
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/b15b942e21531e2252726ee6d0e37425be6977fa/project/frontend_views/views.py#L49
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/b15b942e21531e2252726ee6d0e37425be6977fa/project/frontend_views/views.py#L130
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/b15b942e21531e2252726ee6d0e37425be6977fa/project/frontend_views/views.py#L132-L134
    - [ ] Remove `location` variable https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L388-L392
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L402-L404
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L43
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L45-L47
    - [ ] Remove only level and state fields https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L357

- [ ] Remove state and level fields from serializers:
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/serializers.py#L111-L112
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/serializers.py#L141-L142
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/serializers.py#L180-L181
- [ ] create database migrations with `python manage.py makemigrations`

**Comment by xsraut** [comment]
This is my first time, I'll Try.

**Comment by gorkemarslan** [comment]
@xsraut, I'm assigning you to this issue.

**Comment by brylie** [comment]
@gorkemarslan could you please help double-check that I didn't miss any code? I'm working on a couple of issues at the same time and my focus on this issue was a bit thin.

- state code search: https://github.com/CiviWiki/OpenCiviWiki/search?q=state
- level code search: https://github.com/CiviWiki/OpenCiviWiki/search?q=level
- US_STATES: https://github.com/CiviWiki/OpenCiviWiki/search?q=US_STATES

**Comment by xsraut** [comment]
Thanks @gorkemarslan

**Comment by xsraut** [comment]
Task 1 completed : Removed U.S.-centric code from the project

**Comment by gorkemarslan** [comment]
@xsraut, one pull request is enough for all tasks. So could you also commit requested changes in Task 2 for PR #1107? It would be better if PR #1107 includes all solutions for this task.

I'm also looking at the project to check whether additional tasks can be added to this issue.

**Comment by xsraut** [comment]
Understood, Thank You.

**Comment by sreejithliterally** [comment]
Hi I'm a beginner trying to solve this issue, how can I start?

**Comment by gorkemarslan** [comment]
I reopen this issue because JS part still includes `level` and `state` fields. Since they were removed, there occurs an error when creating a new `thread`.
