### ISSUE TITLE
Port `accounts` app templates to Django template syntax

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1151]
We want to simplify the CiviWiki project by removing JavaScript SPA code written in Backbone.js and using Django templates instead. We will work through the Backbone templates in the `accounts` app to convert the template syntax from Backbone to Django. We want to maintain the visual styling. Below is a checklist of the relevant Backbone templates to be ported to complete this task.

Note: Backbone markup can be found between `{% verbatim %}` and `{% endverbatim %}` template tags as well as within `{% block backbone_template %}`.

## Task

Port the following templates to Django template syntax and ensure they render correctly via the relevant Django view. 

**Note:** all template baths below start within the `accounts/template/accounts/` directory, for brevity.

- [x] #1199
- [x] complete the following for `settings.html`
    - [x] create view for "Save Changes" form submission
    - [x] create view for "delete account" submission
    - [x] use vanilla JS confirm for "delete account" confirmation dialogue
- [x] convert Backbone view models to Django view/model in the following templates
    - [ ] `feed.html` - moved to `threads` app for follow-up work
    - [x] `settings.html`
- [x] ensure the following properties exist on the `User` or `Profile` model
    - [x]  `civis`
    - [x] `followers`
    - [x] `following`
    - [x] `categories`
    - [x] `threads`
    - [ ] `drafts`
- [x] convert API views to Django views
    - [x] `edit_user`
    - [x] `delete_user`
    - [x] `upload_profile_image`
    - [x] `clear_profile_image`
    - [x] `request_follow`
    - [x] `request_unfollow`
    - [x] `edit_user_categories`
- [x] simplify accounts views so there is only one `ProfileEdit` view
- [x] remove `ProfileActivationView`
- [x] remove `ProfileSetupView`
- [x] delete `user_setup.html` and any related routing logic (such as where we force the user through the setup wizard)
    - for simplicity, let's deprecate the setup wizard in favor of `update_settings.html`
- [ ] optionally, add `translate` tags for all accounts UI texts

**Comment by AbhijithGanesh** [comment]
@brylie I would like to work on this!

**Comment by brylie** [comment]
Thanks @AbhijithGanesh. I've assigned you.

We probably need to break the task down into several sub-tasks, due to the number of related changes. In any case, go ahead and start around the top of the list and see what you uncover :smiley:

**Comment by brylie** [comment]
@AbhijithGanesh please note that this task is currently blocked by #1153

**Comment by AbhijithGanesh** [comment]
@brylie I hope this has been opened up

**Comment by brylie** [comment]
@AbhijithGanesh, yes. Issue #1153 has been closed.

**Comment by AbhijithGanesh** [comment]
@brylie I can't checkbox the tasks

**Comment by brylie** [comment]
@AbhijithGanesh try now.

**Comment by AbhijithGanesh** [comment]
Thank you

**Comment by gorkemarslan** [comment]
> create new views (ideally class-based views) as needed to power the multiple tabs and forms available in the user account section

@brylie could they clarify this section? Which views should we create?

**Comment by brylie** [comment]
The key phrase is "as needed", which may include the possibility that no new views are needed. The goal is to build the account templates using Django views/template syntax. The specifics are up to the developer.

Perhaps it would be easier to just build the remaining account templates from scratch without regard to the existing Backbone code?

**Comment by brylie** [comment]
@AbhijithGanesh I've split out the tasks for `feed.html` and `account.html` into sub-tasks. I've listed the blocks of `verbatim` code that need to be ported from Backbone to Django template syntax in the corresponding tasks.

**Comment by brylie** [comment]
@gorkemarslan, were you recently working on this task?

**Comment by gorkemarslan** [comment]
Yes, but I worked only on the first task.

**Comment by brylie** [comment]
Yes, I had forgotten that you were working on a different task. Sorry for the confusion. :smiley:

**Comment by brylie** [comment]
I'll take a look at this task today and start a PR.

**Comment by brylie** [comment]
Note: my goal is to remove the `accounts` Backbone JS while preserving templates and view code. That way, we can re-implement the features as a community, possibly during Hacktoberfest. Also, the Backbone JS is a significant blocker, so this PR will remove the blocking code/complexity.

**Comment by gorkemarslan** [comment]
@brylie, you don't have to migrate all views. I think you are already aware of that but let me write down my thoughts to recap our strategy once again. 😄  For example, we don't use `get_card()` view [anymore](https://github.com/CiviWiki/OpenCiviWiki/pull/1393/files#diff-a5768efd0433161392de5509bf5750338af021185fc6153bfab491e4082f2b9dL155). I forgot to remove this view and the related URL from the project in my MR. Could you remove its implementation? Moreover, I believe we can get rid of all `get_<smt>()` views  in `accounts/api.py` without any replacement.

There is no useful case to keep `get_user()` and `get_profile()`. We should never return the user model. But we can access the user model in all Django templates. The thing is, we can get the user profile from the user model. So no need to use them. If any JS code calls get_user or get_profile we can drop that section.

`edit_user`, `upload_profile_image`, `clear profile image`, `edit_user_categories` can be combined in one view. These all can be updated by only one POST request. Maybe we can put `request_follow` and `request_unfollow` to this new view. It is also possible to create a new dedicated view like `FollowStatusView` to follow and unfollow a user.

We can remove get_feed. As a side note, its implementation is wrong. It returns all threads, not all threads of a user. So basically it is ThreadListView. Also, it is not related to accounts app. Such an implementation should be in threads app.

`ProfileManager` is redundant. Its purpose is to prepare JSON data to send to Backbone.js. Same is true for all model managers in the project. (ThreadManager, CiviManager, CiviImageManager) but for the model managers in thread app let me finish #1152. I ported everything to Django template syntax but the difficult part is to keep the design the same. The project is heavily dependent on JS and I don't want to lose the design. What I try to do to keep the design the same as much as possible. I like your idea to separate account.html file into dedicated HTML files. I am gonna follow your idea in my branch.

**Comment by kobistar** [comment]
Hello,
@brylie Can I assign issue #1151 ?, but I will only convert API views to Django views.

**Comment by brylie** [comment]
@kobistar, thank you for offering to help with this issue. Due to the complexity, I'd like to continue working on this task. Once the task is complete, we should be able to open some new issues with a much smaller size that would be good for Hacktoberfest/first issues.
