### ISSUE TITLE
Port `threads` app templates to Django template syntax

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1152]
We want to simplify the CiviWiki project by removing JavaScript SPA code in Backbone.js and using Django templates instead. We will work through the Backbone templates in the `threads` app to convert the template syntax from Backbone to Django. We want to maintain the visual styling. Below is a checklist of the relevant Backbone templates to be ported to complete this task.

**Note:** Backbone markup is written between `{% verbatim %}` and `{% endverbatim %}` template tags.

## Task

Port the following template from Backbone to Django view/template syntax.

- [ ] convert API views to Django views (if necessary)
  - [ ] `new_thread`
  - [ ] `get_thread`
  - [ ] `get_civi`
  - [ ] `get_civis`
  - [ ] `get_responses`
  - [ ] `create_civi`
  - [ ] `rate_civi`
  - [ ] `edit_civi`
  - [ ] `delete_civi`
  - [ ] `edit_thread`
  - [ ] `upload_civi_image`
  - [ ] `upload_thread_image`

- [ ] threads app shouldn't use Django REST framework
  - [ ] remove `threads/api.py` file

- [ ] threads app should contain only Class Based Views
  - [ ] convert Functıon Based Views to CBVs
  - [ ] convert ViewSets to CBVs

- [ ] all templates in `threads` app should
  - [ ] work without any JavaScript (Backbone.js)
  - [x] use only Django template syntax, such as `{% for solution in solutions %}`

- [ ] all templates in `threads` app should not contain any
  - [x] Backbone.js template syntax, such as `{{# _.each(solutions, function (s) { }}`
  - [x] `verbatim` tags
  - [x] `backbone_templates` block content

**Comment by sreejithliterally** [comment]
@brylie I would like to work on this issue, can I give it a try? Btw I'm a beginner

**Comment by brylie** [comment]
@sreejithdikru, sure. I'll assign you to the task. Please let us know if you have any difficulty with Backbone or Django templates. We can co-assign another person to the issue to assist.

**Comment by wassafshahzad** [comment]
Hi @brylie  I have gone over this issue and this is more complex then I first thought. I will create further issue after breaking this down into independent steps

**Comment by AmarDeepak** [comment]
@brylie I am highly interested to work on this as it is one of my daily tasks to migrate applications from other languages to python frameworks like Django, Flask, FASTAPI, and so on.

**Comment by brylie** [comment]
@AmarDeepak, your help would be much appreciated! Porting from Backbone to Django templates syntax is our most challenging task currently :smile:

**Comment by AmarDeepak** [comment]
@brylie - Thanks for assigning this task to me. 
This weekend I will try to finish as much as I can. My availability maybe a concern as I have to finish my own office work.

**Comment by edwardjimi** [comment]
Hi, I would like to get involved with helping CiviWiki. Could I help?
I'm currently learning Python and Java Script on Code Cademy but have no experience with Backbone or Django.

**Comment by brylie** [comment]
@edwardjimi, thanks for your interest. Let's give @AmarDeepak some time to see how they progress.

**Comment by edwardjimi** [comment]
Thanks for getting back to me @brylie. Happy to help where and when needed.

**Comment by parimalakettymuthu** [comment]
@brylie - looking for a task.. though beginner to Python but having little work experience in other languages.

**Comment by brylie** [comment]
Thanks, @parikvinu. This is a somewhat challenging task since we need to convert templates from Backbone to Django syntax and prepare the template context in Django views. Would you like to give it a try?

**Comment by parimalakettymuthu** [comment]
@brylie  - sure. Can give it a try. Are there any sample templates to refer to?

**Comment by parikvinu** [comment]
@brylie -- following are the blocks of verbatim for the threads.html file -- 

thread-template
thread-wiki-template
edit-wiki-template
thread-nav-template
thread-body-template
thread-response-template
profile-button-template
civi-template
response-template
new-civi-template
new-response-template
Edit-thread-template 

I meant the Django templates (migrated ones) for referring on code structure and modularization..

**Comment by brylie** [comment]
@parimalakettymuthu basically, we can create the templates from scratch or borrow from the existing Backbone code, which is primarily HTML. We can use the Django documentation for reference related to the [Django template syntax](https://docs.djangoproject.com/en/4.0/ref/templates/language/).

**Comment by LexxLuey** [comment]
Is this issue still open?

**Comment by brylie** [comment]
@LexxLuey, yes.

**Comment by LexxLuey** [comment]
Please assign the task to me. I would love to contribute. I have time on my hands

**Comment by brylie** [comment]
Thanks @LexxLuey! Feel free to make the threads app from scratch rather than wrestling with the Backbone code.

**Comment by godfreyJo** [comment]
Here to give a helping hand

**Comment by brylie** [comment]
Thanks @godfreyJo. @LexxLuey, how can @godfreyJo be of assistance?

**Comment by LexxLuey** [comment]
Oh most definately... is there a medium where we can have an online meet concerning the task @godfreyJo @brylie?

**Comment by LexxLuey** [comment]
@brylie he can help me rewrite the view for the page. @godfreyJo, is it possible to sync up anytime soon via a virtual meet?

**Comment by godfreyJo** [comment]
@LexxLuey I am okay, I wonder if you are okay for a quick one in the next 10 minutes.  you can schedule and share the link: godfreyoyugi@gmail.com

**Comment by abdz-128** [comment]
Hi,
I am new here looking for easy open source projects. Willing to help out in Python and Cpp.

**Comment by brylie** [comment]
Welcome @abdz-128 

Please feel free to introduce yourself here:

https://github.com/CiviWiki/OpenCiviWiki/discussions/995

**Comment by abdz-128** [comment]
@brylie Okay 
Introduced myself over there

**Comment by ksharma20** [comment]
Is there something, I can help with, too ? @brylie

**Comment by gorkemarslan** [comment]
I'd like to take over this task.

**Comment by gorkemarslan** [comment]
@brylie, I will move `accounts/feed.html` file to `threads` app. Then I will port the template to Django template syntax. The template basically renders thread list, trending issues, draft threads, etc.

I am planning to create `ThreadListView` to render this template. In this case, I will rename the template file to `thread_list.html` or `threads.html`. I can also keep using `FeedView`. What do you think of the naming?

**Comment by brylie** [comment]
Thanks that will help. :smiley: 

I'm heading to bed now, but I'll check for more comments ASAP.

**Comment by Nehemiah60** [comment]
Hello, @brylie. I see this issue is still open. Also, I have gone through the codebase, and the issues have not been fixed yet. Can you assign me, please?

**Comment by Nehemiah60** [comment]
Hello, @brylie. I think the only task is deleting the api.py file in the threads app. All the other tasks seem to be completed.

**Comment by brylie** [comment]
@gorkemarslan, can you confirm the status of this issue?

**Comment by Nehemiah60** [comment]
I will take this @brylie. I will make the necessary changes where necessary

**Comment by chickenleaf** [comment]
hello @brylie , is this issue or any other issue that is beginner open source friendly up for grabs? i love this project!!
