### ISSUE TITLE
Create view to show a list of followed users

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1200]
Currently, our REST API allows users to follow one another.
https://github.com/CiviWiki/OpenCiviWiki/blob/dc96f00a949f29fad3f55d1b66f3107a94647ab6/project/accounts/urls/api.py#L13-L14

We would like to add a Django view to show a list (or grid) of users that a given user follows. E.g., "user 1" would see a list of all the users they have followed.

## Task

- [ ] add a view called something like `MyFollowedUsers` that returns a list of users the `request.user` has followed
    - https://github.com/CiviWiki/OpenCiviWiki/blob/dc96f00a949f29fad3f55d1b66f3107a94647ab6/project/accounts/views.py 
- [ ] add a URL to call the `MyFollowedUsers` view at `/users/following` or something similar
    - https://github.com/CiviWiki/OpenCiviWiki/blob/dc96f00a949f29fad3f55d1b66f3107a94647ab6/project/accounts/urls/urls.py 
- [ ] define the view template to render the list of usernames returned from the view
    - https://github.com/CiviWiki/OpenCiviWiki/tree/dc96f00a949f29fad3f55d1b66f3107a94647ab6/project/accounts/templates/accounts

**Comment by anurag629** [comment]
Hey, is this issue is resolved or not

**Comment by brylie** [comment]
The issue remains open. The best path forward is likely to build a simple "thread.html" from scratch using Django template syntax, rather than porting the existing Backbone.js code.

**Comment by i-m-karanagarwal** [comment]
Hy @brylie, I would like to work on this. Could you assign this to me? And also please brief me about the files that I may use to fix this.

**Comment by brylie** [comment]
@i-m-karanagarwal, I added more details about the task in the description and links to the relevant files.

**Comment by Walexero** [comment]
Hello @brylie would be willing to work on this issue if its still open

**Comment by brylie** [comment]
This issue is currently assigned to @i-m-karanagarwal

**Comment by Walexero** [comment]
okay

**Comment by i-m-karanagarwal** [comment]
Hy @brylie, Do I need to make changes here in order to show the followed users??

![Screenshot from 2022-10-07 00-00-21](https://user-images.githubusercontent.com/77572300/194391665-ff6e2ee4-b17e-4be1-b607-c98504715274.png)

**Comment by i-m-karanagarwal** [comment]
And also I got these errors while the script
![Screenshot from 2022-10-07 00-03-42](https://user-images.githubusercontent.com/77572300/194391838-a5d691df-e4d2-49c5-8c5c-783cab251669.png)
 manage.py is running

**Comment by brylie** [comment]
I'm not sure what might be causing session corruption.

@gorkemarslan, have you seen any errors like those pictured above?

**Comment by gorkemarslan** [comment]
I will be investigating what causes this issue an try to open a PR to fix it.

Edit: This generally happens because of change in SECRET_KEY. We have recently changed how to get the secret key from .env file. I try to make further improvement to fix it. 👍

**Comment by i-m-karanagarwal** [comment]
> Hy @brylie, Do I need to make changes here in order to show the followed users??
> 
> ![Screenshot from 2022-10-07 00-00-21](https://user-images.githubusercontent.com/77572300/194391665-ff6e2ee4-b17e-4be1-b607-c98504715274.png)

??

**Comment by brylie** [comment]
@i-m-karanagarwal, I believe the list of followed users would display on the "Following" tab.

**Comment by PrakharMundra** [comment]
Hi 
Is this open
Would love to work on it

**Comment by brylie** [comment]
The issue is currently assigned to @i-m-karanagarwal and is blocked by pull request #1428

**Comment by Nehemiah60** [comment]
This issue is also completed @brylie
