### ISSUE TITLE
Update Testing Guide

### ISSUE THREAD

**Issue by ZaidKhan2002** [CiviWiki/OpenCiviWiki#1201]
### Description

I was going through the readme file to the setup project there towards bottom when I saw testing guide after clicking  it redirects to Github 404 error.

### What should have happened?

Either the link should be redirected to testing guide or it should be removed if there is no testing guide.

### Tasks

- [ ] Remove [Testing](https://github.com/CiviWiki/OpenCiviWiki#testing) section from [README.md](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/README.md) file
- [ ] Add `Run unit tests` section under the section of [Run the server](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/CONTRIBUTING.md#run-the-server) in [CONTRIBUTING.md](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/CONTRIBUTING.md) file
- [ ] Add testing guide for our project. For example:
```
cd project && python manage.py test
```

**Comment by gorkemarslan** [comment]
@brylie, in the old branches, we had [testing.md](https://github.com/CiviWiki/OpenCiviWiki/blob/remove-channels/docs/contributing/testing.md) and [contributing](https://github.com/CiviWiki/OpenCiviWiki/tree/remove-channels/docs/contributing) folder. What should be our approach here? Should we recreate the folder and the testing file? What do you suggest?

**Comment by brylie** [comment]
I suppose we can roll the testing instructions into the contributing.md and delete the old documentation links. What are your thoughts?

**Comment by gorkemarslan** [comment]
@brylie, I think so. I edit the issue to create subtasks. Could you edit if you want to add anything new?

**Comment by brylie** [comment]
Looks good! :smiley:
