### ISSUE TITLE
Deprecate setup wizard

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1206]
Deprecate the setup wizard.

## Task

- [ ] users should only fill out a single registration form to sign up
- [ ] users should be automatically logged in when signing up
- [ ] all "setup wizard" code should be removed from project

## Original report

I carried out the following steps:
 - Initialized an user
 - Tried accessing `My Profile`
 - Tried Setting up the user in `setup`

The issue is that, when I access the setup template view, the code breaks. This potentially could mean that we have a malfunctioning code-bit added to our main branch. 

### What should have happened?

The user should have setup the form without much hassle.

### What browser(s) are you seeing the problem on?
All

### Further details

![image](https://user-images.githubusercontent.com/67182544/142751458-baf2d364-e5c8-4745-b732-cbbdd9776c6e.png)

**Comment by brylie** [comment]
In general, I would prefer we deprecate the user setup wizard as it is unnecessarily complex. User registration should be sufficient to interact with the site.

**Comment by mittal-gunjit** [comment]
Did somebody do this already? I was hoping to do this myself but I couldn't replicate the issue. By the way, I am using chrome Version 105.0.5195.125 on an M1 pro chip(ARM 64).

**Comment by brylie** [comment]
I think we can close this issue in favor of the following.

- #1397 
- #1396
