### ISSUE TITLE
enable Rich terminal output

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1347]
## Task

- [ ] add Rich to this project with the command `poetry add rich --group dev`
- [ ] follow the Rich [configuration instructions](https://rich.readthedocs.io/en/stable/introduction.html)
- [ ] add the following code to the `LOGGING = {...}` configuration in the project settings

```py
"formatters": {
    "rich": {"datefmt": "[%X]"},
},
```

```py
"console": {
    "class": "rich.logging.RichHandler",
    "filters": ["require_debug_true"],
    "formatter": "rich",
    "level": "DEBUG",
    "rich_tracebacks": True,
    "tracebacks_show_locals": True,
},
```

**Comment by ApoorvaKashyap** [comment]
Would like to work on this.

**Comment by ApoorvaKashyap** [comment]
Do you only want to show the warnings or every message generated by django?

**Comment by brylie** [comment]
Let's start with errors and warnings.
