### ISSUE TITLE
configure mypy with django-stubs

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1349]
## Task

- [ ] add mypy support in this project with the command `poetry add mypy --group dev`
- [ ] add django-stubbs with the following command `poetry add --group dev django-stubs[compatible-mypy]`
- [ ] add the following configuration to our `pyproject.toml`
- [ ] depending on issue #1331, [enable mypy in our pre-commit settings](https://github.com/pre-commit/mirrors-mypy)
```toml
[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "myproject.settings"
```

**Comment by ApoorvaKashyap** [comment]
Would like to work on this.
