### ISSUE TITLE
replace binary file with markdown

### ISSUE THREAD

**Issue by didiermichel** [CiviWiki/OpenCiviWiki#1358]
### Description

I can see in the repository that there is a binary file `develop/docs/design/CiviWiki_Key_Functionality_Report.odt` 

### What should have happened?

It is not a good practice to save binary in git repository.  It would be better to have a plain text file (md for example) and export it to odt on the fly if you really need it in that format.

## Task

- [x] convert the contents of CiviWiki_Key_functionality_report.odt to Markdown-formatted text
- [x] add the document markdown to a new document in our `docs/` folder
- [x] remove the `odt` document

**Comment by brylie** [comment]
@didiermichel, would you like to convert the document to Markdown text?

**Comment by didiermichel** [comment]
Sure, That would be my pleasure.
I see there is also this odt file:
`/docs/Organization/CiviWiki Privacy Policy.odt`

I can convert them both in markdown file.

I was also wondering if those files are served by the application at some point.

**Comment by brylie** [comment]
The application doesn't serve them. I'm also unsure how relevant the contents are, so converting to Markdown offers an excellent opportunity to check their validity.

**Comment by didiermichel** [comment]
I created PR: https://github.com/CiviWiki/OpenCiviWiki/pull/1389
It is ready for review.
