### ISSUE TITLE
Port all `core` templates to Django template syntax

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1405]
Some templates in our `core` app currently use Backbone.js template syntax.

## Task

Port the following template from Backbone to Django view/template syntax.

all templates in `core` app should
- [ ] work without any JavaScript (Backbone.js)
- [ ] use only Django template syntax, such as `{% for solution in solutions %}`

all templates in `core` app should not contain any
- [ ] Backbone.js template syntax, such as `{{# _.each(solutions, function (s) { }}`
- [ ] `verbatim` tags
- [ ] `backbone_templates` block content

**Comment by dayitachaudhuri** [comment]
Hi, I would like to work on this issue over the weekend. Please assign it to me.

**Comment by gorkemarslan** [comment]
You can start working on it. 👍

**Comment by brylie** [comment]
@dayitachaudhuri, thanks for taking on this task! I'm available to help if you have any questions or difficulties.

**Comment by TimOsahenru** [comment]
I'll also love to work on this if this issue is still open ... please let me know if it is available

**Comment by brylie** [comment]
@dayitachaudhuri is currently assigned to this task.

**Comment by Nehemiah60** [comment]
I will wait in line to work on this issue. If still open, kindly assign it to me. Thanks.

**Comment by Nehemiah60** [comment]
Hello, @brylie. I don't really have significant understanding of js templating, so I don't understand what it is trying to return. So, I am a little bit stuck in this section. For example, in this part where we need to remove the js templating syntax, I have tried fixing it with Django templating syntax but I feel everything is just very wrong...haha below is a sample part I am trying to fix, and after the comment is my solution
![Screenshot (414)](https://user-images.githubusercontent.com/87471613/215533433-52fcdbe0-8fa5-43d6-a973-d572ff01f289.png)
.

**Comment by brylie** [comment]
The code is a for loop that renders a partial template with some data. Just copy the markup from the `notification-item-template` into the loop body in place of the call to `cw.underscorePartial`. From there, it should be more apparent where to use the Django `for` loop and `if` statements.

https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#for 

https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#if 

This might be a good use case for the `for...empty` loop.

https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#for-empty

**Comment by Nehemiah60** [comment]
Hello @brylie . I am trying to make a pull request but there is something strange with the codeclimate bot. For example, there is one issue identified here, which is trailing space as seen below;
![Otek](https://user-images.githubusercontent.com/87471613/215848784-854d7987-b87a-48f0-bacc-d2a63df121a5.png)
However, the same file in my branch looks so different, and it is this
![Screenshot (416)](https://user-images.githubusercontent.com/87471613/215849034-92742e0a-f1eb-4e21-b731-ee28a6e30f3f.png)

**Comment by Nehemiah60** [comment]
Hello, @brylie I made a PR on this issue. Kindly, have a look. Thanks.
https://github.com/CiviWiki/OpenCiviWiki/commit/98fb90db66e5f69009182c9f3e553eee4f04d9a0

**Comment by Nehemiah60** [comment]
Hello @brylie. I made a new PR. If there are more issues, then I will surely need some guidelines to fix them properly. Thaks
[2a55488](https://github.com/CiviWiki/OpenCiviWiki/commit/2a55488c08158a99d86c1f5ca5ed5a2e1dfcef3e)

**Comment by Nehemiah60** [comment]
Hey, @brylie. I just realized that there may be an issue with my PR. I mean, there needs to be only a single block of content in each file. I think my last PR might also have an issue.

**Comment by Nehemiah60** [comment]
Here it is @brylie 
https://github.com/CiviWiki/OpenCiviWiki/pull/1494#pullrequestreview-1284035120

**Comment by Nehemiah60** [comment]
Hey @brylie. I made the necessary changes here [ac3a41b](https://github.com/CiviWiki/OpenCiviWiki/commit/ac3a41b063de466b32f1273ce0487adc271fcca4)

**Comment by Nehemiah60** [comment]
Hey @brylie here is the new PR.[6f969c9](https://github.com/CiviWiki/OpenCiviWiki/commit/6f969c9fd34728f0f92ee8cf20db3ea220ba375a)

**Comment by Nehemiah60** [comment]
Hey @brylie I made the changes in this new PR. [fb7e2d1](https://github.com/CiviWiki/OpenCiviWiki/commit/fb7e2d1550fb25ec269cfbb485be54d3f1b6c2c6)
