### ISSUE TITLE
Research standards-based frameworks for web UI components

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1406]
### Idea summary

We need a standards-based (i.e., CSS, HTML, and Web Components) approach to defining UI components.

## Constraints

Any UI design system pattern library or framework adopted by this project should be:

- simple (avoid build tools and other complexities if possible)
- standards-based (use only CSS, JS, HTML, Web Components, and related standards defined by W3C/WHATWG)
- batteries-included (would ideally provide ready-made components rather than more primitive "utilities")
- decluttered (HTML templates should remain pretty clean without a lot of aesthetic descriptors)
- fully open source (no pro version upgrades or proprietary components)

Note: our design mockups use Material Design so a material design library may be desirable.

## Task

- [ ] research standards-based tools/frameworks for creating UI design systems
- [ ] locate any existing component libraries/design systems that we may use, with the ability to modify them as needed
- [ ] document/discuss your findings in this issue so we can compare the options

**Comment by brylie** [comment]
@srishti666, would you like to work on this task?

**Comment by srishti666** [comment]
I would love to work on this but cannot understand the task. Actually, I'm a beginner so I'm having problems.

**Comment by brylie** [comment]
@srishti666, would you like to be a beta tester and find potential bugs? If so, I can create a task specifically for you.

**Comment by srishti666** [comment]
No thanks, I think I'm not fit for this task
