### ISSUE TITLE
Add "Followers" tab to the user profile view

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1446]
We recently removed some features from the user Profile view and now want to reimplement them using only Django.

This task will be to add a "Followers" tab to the user profile view. The tab should link to a sub-path of the user profile so it is clear to the viewer that they are viewing followers related to the user.

## Task
All of these tasks should be done in the `accounts` app.

- [ ] create a Django view called `UserFollowers` (in `accounts/views.py`)
- [ ] create a URL definition `profile/<str:username>/followers` that renders the `UserFollowers` view ( in `accounts/urls.py`)
- [ ] ensure the `UserFollowers` view context contains a list of users that are following the relevant user (given via the `username` in the URL) 
    - note, it should be possible to get the followers via `user.profile.followers` or just `profile.followers`
- [ ] create a template to render the user followers - for now, extending `base.html` so we have consistent branding  (in `accounts/templates/accounts/user_civis.html`)

**Comment by BrunoFNRodrigues** [comment]
I'd like to work on this issue.

**Comment by Nehemiah60** [comment]
I had requested to work on the Issues tab. I have realized that I need to complete, the followers tab, following, and then on the issues. Can, I start working on this, please?

**Comment by Nehemiah60** [comment]
If these changes were merged I am still unable o see, the followers tab here with me. Maybe may you clarify on this, please? I am trying to understand this a little bit

**Comment by Nehemiah60** [comment]
Do you have a minute, please? I can create a 5-minute video call. Let me know if it's possible, I can share a video link. Thanks.
