### ISSUE TITLE
Add "Following" tab to the user profile view

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1447]
We recently removed some features from the user Profile view and now want to reimplement them using only Django.

This task will be to add a "Following" tab to the user profile view. The tab should link to a sub-path of the user profile, so it is clear to the viewer that they are viewing users that a particular user is following.

## Task
All of these tasks should be done in the `accounts` app.

- [ ] create a Django view called `UserFollowing` (in `accounts/views.py`)
- [ ] create a URL definition `profile/<str:username>/following` that renders the `UserFollowing` view ( in `accounts/urls.py`)
- [ ] ensure the `UserFollowing` view context contains a list of users that the relevant user is following (given via the `username` in the URL) 
    - note, it should be possible to get profiles that the user follower via `user.profile.following` or just `profile.following`
- [ ] create a template to render the followed usernames - for now, extending `base.html` so we have consistent branding  (in `accounts/templates/accounts/user_civis.html`)

**Comment by wippo-devops** [comment]
I would like to work on this.

**Comment by belalmn-cmu** [comment]
Regarding the newly created following tab, I noticed that there were no added unit testcases provided in the accounts/views_tests.py

We've created some testcases that are consistent with other provided testcases. I'd like to provide these as a new PR.

Please let me know if this is possible and/or if we need to create a new issue for this implementation.

**Comment by brylie** [comment]
Sure thing, thanks! Just open the new pull request and link it to this issue.

**Comment by Nehemiah60** [comment]
Hello @brylie. Is this issue still open? I will love to work on this issue. Thanks.

**Comment by Nehemiah60** [comment]
Hello, @brylie. I think this issue has been solved already. There is a ProfileFollowing class that renders the users that a specific user is following.

**Comment by brylie** [comment]
Ok cool beans
