### ISSUE TITLE
Add "Issues" tab to the user profile view

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1448]
We recently removed some features from the user Profile view and now want to reimplement them using only Django.

This task will be to add an "Issues" tab to the user profile view. The tab should link to a sub-path of the user profile so it is clear to the viewer that they are viewing Issues related to the user.

## Task
All of these tasks should be done in the `accounts` app.

- [ ] create a Django view called `UserIssues` (in `accounts/views.py`)
- [ ] create a URL definition `profile/<str:username>/issues` that renders the `UserIssues` view ( in `accounts/urls.py`)
- [ ] ensure the `UserIssues` view context contains a list of users that are following the relevant user (given via the `username` in the URL) 
    - note, it should be possible to get the issues via `user.issue_civis`
- [ ] create a template to render the user issues - for now, extending `base.html` so we have consistent branding  (in `accounts/templates/accounts/user_civis.html`) 
    - unless the `profile_base.html` is available, in which case use that instead

**Comment by 8bitaby** [comment]
Can you please assign this issue to me?

**Comment by werberger** [comment]
Again, can I put my hand up for next in line? No pressure @8bitaby 

@brylie is it just spam if I put the same comment in the other two similar issues?

**Comment by brylie** [comment]
@werberger, since most of the CiviWiki issues have been claimed, would you like to take a task in another open-source project? I'm also developing Companionship Care, and there are several open issues marked as "help wanted":

[[werberger](https://github.com/werberger)](https://github.com/CompanionshipCare/companionship-care/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)

**Comment by Nehemiah60** [comment]
Can I be next in line for this issue? I'd like to work on this issue

**Comment by brylie** [comment]
Sure. Open a pull request when you've got some initial progress 🙂

**Comment by Nehemiah60** [comment]
I would love your feedback on this. I made a PR and I am awaiting a response. If there is an issue, I would love your support in tackling it. Thanks.

**Comment by brylie** [comment]
What is the link to the PR you created?

**Comment by Nehemiah60** [comment]
https://github.com/Nehemiah60/OpenCiviWiki/branches

**Comment by brylie** [comment]
Ah, OK. That looks like the list of branches in your GitHub fork. Once you have committed some changes to the `issues-tab` branch, go ahead and follow the instructions for opening a GitHub pull request:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by Nehemiah60** [comment]
I had forgotten to create a pull request after committing the changes. I will love the feedback, and also support if there is revision needed. Thanks.

**Comment by Nehemiah60** [comment]
Here it is...there were some issues I was trying to fix.
https://github.com/CiviWiki/OpenCiviWiki/pull/1491

**Comment by Nehemiah60** [comment]
I hope it can be accessed now.
