### ISSUE TITLE
Reimplement user categories feature

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1451]
We recently removed some features from the user Profile view and now want to reimplement them using only Django.

This task will be to add a "categories" field to the User Profile ("settings") view).

## Task

All of these tasks should be done in the `accounts` app.

- [ ] determine how to add a multi-select field to a Django form
- [ ] users should be able to select zero or more categories when editing their profile
- [ ] when a user updates their categories, the categories should be listed on the user profile page

**Comment by TimOsahenru** [comment]
Hello @brylie I'll love to work on this issue please assign it to me.

**Comment by TimOsahenru** [comment]
Hello @brylie haven't heard from you, please 
should I go ahead?

**Comment by brylie** [comment]
@TimOsahenru, thanks for taking this issue. I'll assign you.

Please keep in mind that people are working in different time zones worldwide and typically in their spare time, so they might not be able to respond immediately when mentioned.

**Comment by TimOsahenru** [comment]
Hello @brylie I am having a bit of a challenge displaying the list of categories; the issue is, it just display's as a plain list instead of a clickable selective list, please I need assistance on how to execute this, below is a screenshot of my code and a description of my challenge. Please I need your assistance

![1](https://user-images.githubusercontent.com/93861430/199154757-d7ef0518-44aa-4d98-9b9b-bbfce084f58b.png)

![2](https://user-images.githubusercontent.com/93861430/199154773-58ea0cbb-cd07-490d-ace5-c6b1fc3d6030.png)

**Comment by brylie** [comment]
Go ahead and commit your code, push the changes to GitHub, and open a pull request where we can discuss the code. That will help move the discussion forward since reviewers can also check out your code.

I think the solution may be to use the ModelMultipleChoiceField:

https://docs.djangoproject.com/en/4.1/ref/forms/fields/#modelmultiplechoicefield

**Comment by Nehemiah60** [comment]
Is this issue closed? I would love to handle this issue

**Comment by brylie** [comment]
@Nehemiah60 this issue is still open. Please review the discussion and try to carry forward the existing pull request.

**Comment by Nehemiah60** [comment]
Hello, @brylie I made a PR on this issue. If you get time kindly review it, and I will appreciate your feedback. Thanks.
https://github.com/CiviWiki/OpenCiviWiki/pull/1493
