### ISSUE TITLE
Create a base template used for all UserProfile sub-views

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1452]
We recently removed some features from the user Profile view and now want to reimplement them using only Django.

This task will be to add a base template, extending `base.html`, that is used for all sub-views of the user profile.

## Task
All of these tasks should be done in the `accounts` app.

- [x] create a new template `accounts/templates/accounts/user_profile_base.html`
- [x] make sure the `user_profile_base.html` extends `base.html`
- [x] add a block called `content`, if it is possible to shadow block names, otherwise call it `profile_content`

## Example code

The `user_profile_base.html` will probably look similar to the following. Note that this new base template will have very few lines of code.

```html
{% extends "base.html" %}

{% block extra_css%}{% endblock extra_css %}

{% block content %}{% endblock content %}

{% block extra_js %}{% endblock extra_js %}
```

**Comment by aidanmatchette** [comment]
Hey is this issue ope?If so I would like to take it.

**Comment by brylie** [comment]
Thanks @aidanmatchette. I'll assign you :-)
