### ISSUE TITLE
Set up continuous integration to run automated tests aganst pull requests

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#146]
In order to promote quality and confidence when shipping new features, we should have a continuous integration system run automated tests against our pull requests.

# Task
- [ ] determine how to run automated tests via command line
- [ ] choose continuous integration framework for our project
  - should support our test suite
  - should integrate with GitHub pull requests
- [ ] configure continuous integration to run our automated test suites when contributors push to development branches

**Comment by abossenbroek** [comment]
For automated testing would you be interested in Pytest or nose?

Happy to contribute with Docker files and docker compose to set up the testing environment and work on continuous integration on circle ci and/or travis.

**Comment by brylie** [comment]
What are the pros/cons of Pytest vs. nose? I am not very familiar with either.

**Comment by brylie** [comment]
This was on the Nose documentation:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

**Comment by brylie** [comment]
My intuition is saying Pytest, but I will wait to hear your perspective.

**Comment by abossenbroek** [comment]
I would recommend Pytest. It allows for export of test results to xml which allows for smoother integration with CI tools such as [circleci](https://circleci.com).

Happy to write a docker file to incorporate Redis, Postgres. This would ultimately make it easier also for new developers to start the entire app at once. I currently don't see that as a task on waffle but IMHO it would like help in setting up a CI tool.

**Comment by brylie** [comment]
> Happy to write a docker file to incorporate Redis, Postgres. This would ultimately make it easier also for new developers to start the entire app at once. I currently don't see that as a task on waffle but IMHO it would like help in setting up a CI tool.

I added the task #157. Would you please assign yourself to the task?

**Comment by brylie** [comment]
@mdwest I think we should prioritize this issue.

**Comment by mdwest** [comment]
I support prioritizing this but was hoping to get version 3 online first.

**Comment by brylie** [comment]
Jep, that makes sense. The [0.2 roadmap](https://github.com/CiviWiki/OpenCiviWiki/milestone/2) is nearing completion. There are just a couple of large-ish outstanding issues.

**Comment by brylie** [comment]
Closing as superceded by #1024
