### ISSUE TITLE
Create linear linking relationships between Civis

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#149]
In order to continue with #101, we agreed to implement a linear linking 'hierarchy' between Civis.

Simplified linking: Problems link to nothing. Causes Link to Problems, Solutions link to Causes.

# Task
- [ ] Create data model for each Civi type
  - [ ] `Problem`
  - [ ] `Cause`
  - [ ] `Solution`
- [ ] Create many-to-many relationships between models to reflect the desired structure - including the inverse relationship
  - [ ] `Problem` -caused_by ->`Cause`  
  - [ ] `Cause` -causes-> `Problem`
  - [ ] `Solution` -solves-> `Cause`
  - [ ] `Cause` -solved_by-> `Solution`
- [ ] Create API endpoints for the new models using Django REST Framework
-

**Comment by jl24** [comment]
@brylie how should we go about making the data models? I was thinking either to make the current `Civi` model into an abstract model and then have each of the civi types inherit from that as their own models. Wondering if you had other better ideas.

**Comment by brylie** [comment]
Yeah, the abstract base class seems like a good idea. What do they recommend in Two Scoops of Django (1.11)? The difference between the models would be mainly the foreign key relationship, which would enforce the directionality of the graph.

**Comment by reedjones** [comment]
I added some graph relationships among other things See my branch here https://github.com/reedjones/OpenCiviWiki/tree/add-graph-relationships
