### ISSUE TITLE
Dockerize CiviWiki project (and dependencies)

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#157]
Continuing discussion from #146 

It was pointed out that creating Docker containers for CiviWiki and/or its dependencies would make the following easier:

- setting up new development environments
- setting up/running continuous integration

It may also allow us more flexibility when deploying CiviWiki to stages, such as production.

# Task
- [ ] determine best combination of Docker container(s) for CiviWiki and its dependencies
- [ ] determine current best practices about Docker container definition formats (e.g. comparing Docker Compose, Kubernetes Helm, Rancher, etc.)
- [ ] choose appropriate Docker format for CiviWiki project goals (outlined above and through discussion)
- [ ] create Docker container(s) for CiviWiki project and/or components (such as Redis and PostgreSQL)

**Comment by abossenbroek** [comment]
Started some work on commit 7bee1f350661b4ca7b1385c74df444394256c0c8 The reliance on `requirements.txt` causes some specific installations of libraries in the docker container; I have very good experience with miniconda to overcome these kind of issues. For now I tried to lock down as many settings as possible.

For docker I use [phusion image](https://github.com/phusion/baseimage-docker) so that the container is a bit more robust. 

I was also required to upgrade `psycopg2` to resolve an issue with dependency on Postgres 10.

Next up is following guidelines specified [here](https://github.com/hackoregon/civic-devops/issues/12) to store secrets connecting database to Django.

**Comment by brylie** [comment]
What do you think about using Pipenv instead of requirements.txt?

**Comment by brylie** [comment]
> I was also required to upgrade psycopg2 to resolve an issue with dependency on Postgres 10.

What does the project use psycopg2 for? Can we consider removing that dependency?

**Comment by brylie** [comment]
> Where do you want to put preference on in terms of first environment to develop?

What do you mean by 'environment'? I.e. Operating System, or something else?

**Comment by brylie** [comment]
Closing since we have a working Dockerfile and docker-compose.yml
