### ISSUE TITLE
Test project with Django 1.11.x

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#23]
Django 1.11 is the latest Long Term Support (LTS) release. Test the project with Django 1.11 and upgrade if possible.

# Goal
Upgrade project to latest Django LTS release.

# Task
- [ ] Deploy [testing branch](https://github.com/CiviWiki/OpenCiviWiki/pull/97) to Heroku
- [ ] Have testers try to find bugs in testing deployment
- [ ] Note any discovered bugs as backlog issues
- [ ] If testing doesn't uncover any bugs, close this issue noting that testing was successful

**Comment by mdwest** [comment]
Is there a server ready to test this? If not, send me a link when there is and I will begin testing.
