### ISSUE TITLE
Use consistent spacing and indentation (Flake8 errors)

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#36]
After running Flake8 (#33), we received several notices about **spaces and indentation** in CiviWiki sourcecode.

# Goal
Use consistent indentation and spacing throughout CiviWiki sourcecode. Conform to guidelines of PEP-8.

# Task
Clean up the following Flake8 errors:

- [x] ./api/read.py:220:60: E272 multiple spaces before keyword                                                                                                                                                                                                                      
- [x] ./api/read.py:220:87: E272 multiple spaces before keyword
- [x] ./api/write.py:499:19: E271 multiple spaces after keyword
- [x] ./api/write.py:502:58: E225 missing whitespace around operator
- [x] ./api/write.py:549:19: E271 multiple spaces after keyword
- [x] ./api/models/civi.py:41:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:41:1: W191 indentation contains tabs
- [x] ./api/models/civi.py:43:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:54:31: E251 unexpected spaces around keyword / parameter equals
- [x] ./api/models/civi.py:65:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:65:1: W191 indentation contains tabs
- [x] ./api/models/civi.py:67:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:116:29: E241 multiple spaces after ':'
- [x] ./api/models/civi.py:124:5: E301 expected 1 blank line, found 0
- [x] ./api/models/civi.py:156:39: E225 missing whitespace around operator
- [x] ./api/models/civi.py:156:42: E221 multiple spaces before operator
- [x] ./api/models/civi.py:166:48: E225 missing whitespace around operator
- [x] ./api/models/civi.py:190:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:190:1: W191 indentation contains tabs
- [x] ./api/models/civi.py:191:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:208:1: E305 expected 2 blank lines after class or function definition, found 1
- [x] ./api/models/account.py:88:1: E305 expected 2 blank lines after class or function definition, found 1
- [x] ./api/models/account.py:169:5: E301 expected 1 blank line, found 0
- [x] ./api/models/thread.py:57:1: E305 expected 2 blank lines after class or function definition, found 1
- [x] ./authentication/forms.py:121:297: E251 unexpected spaces around keyword / parameter equals
- [x] ./authentication/forms.py:121:299: E251 unexpected spaces around keyword / parameter equals
- [x] ./authentication/forms.py:121:316: E251 unexpected spaces around keyword / parameter equals
- [x] ./authentication/forms.py:121:318: E251 unexpected spaces around keyword / parameter equals
- [x] ./authentication/authentication.py:29:5: E301 expected 1 blank line, found 0
- [x] ./authentication/authentication.py:39:1: E305 expected 2 blank lines after class or function definition, found 1

**Comment by brylie** [comment]
@mattyg915 go ahead and open a pull request as soon as you've made your first commit. Try to push your commits at least once a day, so they are available on GitHub for safe keeping.

**Comment by mattyg915** [comment]
Pull request created! I cleaned up the first few files and will work on the rest tonight/this afternoon.

**Comment by mattyg915** [comment]
Should all be done and committed now!

**Comment by brylie** [comment]
@mattyg915 in your pull request description add the following string:

- Closes #36

That string, `Closes #<issue_number>` will associate the PR with the issue. It is one of [several ways to associate GitHub pull requests with issues](https://help.github.com/articles/closing-issues-using-keywords/).
