### ISSUE TITLE
Check project for bugs related to undefined variables

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#38]
When running a Flake8 scan (#33), several errors were reported related to **undefined variables**.

# Goal
Make sure all needed variables are defined in project, to prevent bugs. Pass Flake8 scan, particularly as related to undefined variables.

# Task
Check the following variables to see if/how they should be defined, and resolve the related Flake8 errors:

- [ ] ./frontend_views/views.py:171:55: F821 undefined name 'Topic'                                                                                                                                                                                                                          
- [ ] ./api/read.py:141:37: F821 undefined name 'user'                                                                                                                                                                                                                               
- [ ] ./api/read.py:143:16: F821 undefined name 'user'
- [ ] ./api/read.py:186:13: F821 undefined name 'problems'
- [ ] ./api/read.py:187:27: F821 undefined name 'problems'
- [ ] ./api/write.py:466:55: F821 undefined name 'default'
- [ ] ./api/write.py:618:34: F821 undefined name 'profile'
- [ ] ./api/write.py:672:90: F821 undefined name 'all_categories'

**Comment by extremelypenguin** [comment]
Is this issue still open? i'd be interested in doing this

**Comment by brylie** [comment]
Ok, cool. Have you tried setting up a development environment?

**Comment by delta-plus** [comment]
I tried it on my cloned testing environment with Python 2.7 and Flake8 installed with pip for 2.7. I didn't get any of those errors. Are the Flake8 and Python versions the same? If they don't match, it might be causing the errors.

**Comment by delta-plus** [comment]
Was my solution correct?

**Comment by brylie** [comment]
Well, this task was just to double check. So, yes. :-)
