### ISSUE TITLE
Use explicit relative imports within CiviWiki modules

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#40]
We should use **explicit relative imports** within a module. This promotes portability and readability.

# Goal
Change CiviWiki modules to use relative imports where possible.

# Task
The following files/lines can be changed to use relative imports.

## /api/models/account.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/account.py#L20-L22

## /api/models/activity.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/activity.py#L2-L4

## /api/models/civi.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/civi.py#L2-L5
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/civi.py#L12

## /api/models/notification.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/notification.py#L2-L4

## /api/models/rationale.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/rationale.py#L2-L4

## /api/models/rebuttal.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/rebuttal.py#L2-L3

## /api/models/response.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/response.py#L2-L3

## /api/models/thread.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/thread.py#L2-L6

## /api/models/vote.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/vote.py#L2-L3

## /api/write.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/write.py#L11
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/write.py#L14
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dev/api/write.py#L23

## /api/consumers.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/consumers.py#L4
