### ISSUE TITLE
Reorganize imports to follow best practices

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#41]
Many files in this project have a 'mish-mash' import style, where imports seem to have been added through accretion.

Two Scoops of Django (1.11) recommends that projects adopt the following import ordering:

1. Standard Library imports
2. Django core imports
3. third-party app imports
4. project internal imports

# Goal
Use consistent import ordering throughout project.

# Task
Re-organize imports in the following files:

- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dev/api/models/civi.py#L1-L12
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dev/api/write.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dev/api/tasks.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dev/api/read.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dev/api/models/invitation.py#L4-L7
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dev/api/models/thread.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dev/authentication/authentication.py#L1-L24
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dev/authentication/forms.py#L1-L15
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dev/frontend_views/views.py#L1-L14

**Comment by cjtu** [comment]
I'm interested in contributing and I'd be happy to start here to learn my way around

**Comment by brylie** [comment]
@cjtu thanks for your interest. May I help you get a development environment set up?

**Comment by cjtu** [comment]
Yes please. I had some trouble getting redis going on Windows 10. Does anyone else use Windows? Should I try it with Docker?

**Comment by brylie** [comment]
See if Docker works for you.

Alternatively, you could set up a dev environment in an Ubuntu VM or dual-boot.

https://github.com/felixrieseberg/windows-development-environment

**Comment by mdwest** [comment]
@cjtu Did get your development environment set up? Let me know if you still need help!

**Comment by cjtu** [comment]
Still no luck. I took the bash on ubuntu on windows approach and hit a dead end. I got redis setup but now postgres is giving me trouble. I can connect to it and make roles and databases from bash, but always get the following error when django tries to connect in the setup:

`does not existOperationalError: FATAL: role civiwiki`

I don't really know how to debug this further. I've gone through all the guides I can find on postgres on WSL and tried a workaround using my bash username instead of "civiwiki" but no luck. Any suggestions would be great!
