### ISSUE TITLE
Cleanup commented code

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#42]
In order to keep a clean codebase, we should clean up any code that is not in use. This includes code that has been commented out, without a 'TODO' comment.

# Goal
Keep a tidy codebase by removing commented-out code.

# Task
Clean up the following files/lines that have commented out code.

## /api/models/civi.py
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/civi.py#L99-L100

## /api/models/hashtag.py
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/fact.py#L7

## /api/models/rebuttal.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/rebuttal.py#L4
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/rebuttal.py#L13

## /api/models/representative.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/representative.py#L10

## /api/models/response.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/response.py#L4
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/models/response.py#L14

## /api/read.py
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/read.py#L14-L48
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/read.py#L76-L79
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/read.py#L140
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/read.py#L158-L159
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/read.py#L162-L165
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/read.py#L177-L179
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/read.py#L188-L212
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/read.py#L226-L228

## /api/urls.py
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/urls.py#L6-L10
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/urls.py#L27-L29
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/urls.py#L41-L47

## /api/write.py
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/write.py#L10
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/write.py#L46-L102
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/write.py#L126-L135
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/write.py#L145-L146
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/write.py#L168-L170
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/write.py#L555-L581
- [x] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/api/write.py#L735-L737

## /frontend_views/views.py
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/frontend_views/views.py#L95
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/dbacc71c188135cdd4344aca09813ebb1b70b8a2/frontend_views/views.py#L100-L106

**Comment by tractaylor** [comment]
I didnt see the following lines to remove...
OpenCiviWiki/api/read.py
Lines 188 to 212 in dbacc71

**Comment by brylie** [comment]
> I didnt see the following lines to remove...
> OpenCiviWiki/api/read.py
> Lines 188 to 212 in dbacc71

Here it is:

https://github.com/CiviWiki/OpenCiviWiki/blob/8d24187e9cfa55d7fb37d59990fe529259fd8668/project/api/read.py#L188-L212

**Comment by brylie** [comment]
For what it's worth, we just reorganized the whole repository. Make sure you are committing to files in the `/project` directory now.
