### ISSUE TITLE
Upgrade project dependencies

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#43]
**Note:** the goal of this task is simply to update as many dependencies as possible. Difficult dependencies can be updated in follow-up tasks.

As part of our commitment to ongoing maintenance and security, we can periodically upgrade project dependencies.

# Situation
As of today (2017-08-30), pip shows the following dependencies are outdated:

```
Package                 Version Latest  Type                                                                                                                                                                                                                                   
----------------------- ------- ------- -----                                                                                                                                                                                                                                  
asgi-redis              1.0.0   1.4.2   wheel                                                                                                                                                                                                                                  
asgiref                 1.0.1   1.1.2   wheel                                                                                                                                                                                                                                  
autobahn                17.6.2  17.8.1  wheel                                                                                                                                                                                                                                  
billiard                3.5.0.2 3.5.0.3 sdist                                                                                                                                                                                                                                  
boto                    2.46.1  2.48.0  wheel                                                                                                                                                                                                                                  
celery                  4.0.2   4.1.0   wheel                                                                                                                                                                                                                                  
channels                1.0.3   1.1.6   wheel                                                                                                                                                                                                                                  
cryptography            1.9     2.0.3   wheel                                                                                                                                                                                                                                  
daphne                  1.1.0   1.3.0   wheel                                                                                                                                                                                                                                  
dj-database-url         0.4.1   0.4.2   wheel                                                                                                                                                                                                                                  
Django                  1.8.7   1.11.4  wheel                                                                                                                                                                                                                                  
django-cors-headers     1.1.0   2.1.0   wheel                                                                                                                                                                                                                                  
django-notifications-hq 1.2     1.3     wheel                                                                                                                                                                                                                                  
django-storages         1.5.2   1.6.5   wheel                                                                                                                                                                                                                                  
djangorestframework     3.6.3   3.6.4   wheel                                                                                                                                                                                                                                  
docutils                0.12    0.14    wheel                                                                                                                                                                                                                                  
gunicorn                19.6.0  19.7.1  wheel                                                                                                                                                                                                                                  
h2                      2.6.1   3.0.1   wheel                                                                                                                                                                                                                                  
hpack                   2.3.0   3.0.0   wheel
idna                    2.5     2.6     wheel
jmespath                0.9.0   0.9.3   wheel
kombu                   4.0.2   4.1.0   wheel
Pillow                  3.4.2   4.2.1   wheel
psycopg2                2.6.1   2.7.3.1 wheel
pyasn1                  0.2.3   0.3.3   wheel
pyasn1-modules          0.0.9   0.1.1   wheel
pyflakes                1.5.0   1.6.0   wheel
pyOpenSSL               16.2.0  17.2.0  wheel
python-dateutil         2.4.2   2.6.1   wheel
redis                   2.10.5  2.10.6  wheel
requests                2.8.1   2.18.4  wheel
service-identity        16.0.0  17.0.0  wheel
setuptools              27.2.0  36.3.0  wheel
Twisted                 17.1.0  17.5.0  sdist
txaio                   2.8.0   2.8.1   wheel
vine                    1.1.3   1.1.4   wheel
whitenoise              3.2     3.3.0   wheel
```

[Piprot](https://github.com/sesh/piprot) gives a slightly different summary:

```
Django (1.8.7) is 615 days out of date. Latest is 1.11.4
django-cors-headers (1.1.0) is 741 days out of date. Latest is 2.1.0
djangorestframework (3.6.3) is 101 days out of date. Latest is 3.6.4
docutils (0.12) is 818 days out of date. Latest is 0.14
gunicorn (19.6.0) is 301 days out of date. Latest is 19.7.1
jmespath (0.9.0) is 603 days out of date. Latest is 0.9.3
psycopg2 (2.6.1) is 658 days out of date. Latest is 2.7.3.1
python-dateutil (2.4.2) is 831 days out of date. Latest is 2.6.1
requests (2.8.1) is 672 days out of date. Latest is 2.18.4
whitenoise (3.2) is 244 days out of date. Latest is 3.3.0
dj-database-url (0.4.1) is 273 days out of date. Latest is 0.4.2
Pillow (3.4.2) is 260 days out of date. Latest is 4.2.1
daphne (1.1.0) is 89 days out of date. Latest is 1.3.0
asgiref (1.0.1) is 58 days out of date. Latest is 1.1.2
channels (1.0.3) is 146 days out of date. Latest is 1.1.6
asgi-redis (1.0.0) is 227 days out of date. Latest is 1.4.2
django-notifications-hq (1.2) is 374 days out of date. Latest is 1.3
boto (2.46.1) is 135 days out of date. Latest is 2.48.0
django-storages (1.5.2) is 199 days out of date. Latest is 1.6.5
Twisted (17.1.0) is 119 days out of date. Latest is 17.5.0
h2 (2.6.1) is 17 days out of date. Latest is 3.0.1
pyOpenSSL (16.2.0) is 277 days out of date. Latest is 17.2.0
service-identity (16.0.0) is 460 days out of date. Latest is 17.0.0
idna (2.5) is 154 days out of date. Latest is 2.6
celery (4.0.2) is 220 days out of date. Latest is 4.1.0
```

# Goal
Keep project dependencies up-to-date.

# Task
Update most, or all, of the following dependencies:

- [x] asgi-redis (1.0.0) - Latest: 1.4.2 [wheel]
- [x] asgiref (1.0.1) - Latest: 1.1.2 [wheel]
- [x] autobahn (17.6.2) - Latest: 17.8.1 [wheel]
- [x] billiard (3.5.0.2) - Latest: 3.5.0.3 [sdist]
- [x] boto (2.46.1) - Latest: 2.48.0 [wheel]
- [x] celery (4.0.2) - Latest: 4.1.0 [wheel]
- [ ] channels (1.0.3) - Latest: 1.1.6 [wheel]
- [x] cryptography (1.9) - Latest: 2.0.3 [wheel]
- [ ] daphne (1.1.0) - Latest: 1.3.0 [wheel]
- [x] dj-database-url (0.4.1) - Latest: 0.4.2 [wheel]
- [x] django-cors-headers (1.1.0) - Latest: 2.1.0 [wheel]
- [x] django-notifications-hq (1.2) - Latest: 1.3 [wheel]
- [x] django-storages (1.5.2) - Latest: 1.6.5 [wheel]
- [x] djangorestframework (3.6.3) - Latest: 3.6.4 [wheel]
- [x] docutils (0.12) - Latest: 0.14 [wheel]
- [x] gunicorn (19.6.0) - Latest: 19.7.1 [wheel]
- [x] h2 (2.6.1) - Latest: 3.0.1 [wheel]
- [x] hpack (2.3.0) - Latest: 3.0.0 [wheel]
- [x] idna (2.5) - Latest: 2.6 [wheel]
- [x] jmespath (0.9.0) - Latest: 0.9.3 [wheel]
- [x] kombu (4.0.2) - Latest: 4.1.0 [wheel]
- [x] Pillow (3.4.2) - Latest: 4.2.1 [wheel]
- [x] psycopg2 (2.6.1) - Latest: 2.7.3.1 [wheel]
- [x] pyasn1 (0.2.3) - Latest: 0.3.3 [wheel]
- [x] pyasn1-modules (0.0.9) - Latest: 0.1.1 [wheel]
- [x] pyflakes (1.5.0) - Latest: 1.6.0 [wheel]
- [x] pyOpenSSL (16.2.0) - Latest: 17.2.0 [wheel]
- [x] python-dateutil (2.4.2) - Latest: 2.6.1 [wheel]
- [x] redis (2.10.5) - Latest: 2.10.6 [wheel]
- [x] requests (2.8.1) - Latest: 2.18.4 [wheel]                                                                                                                                                                                                                                      
- [x] service-identity (16.0.0) - Latest: 17.0.0 [wheel]                                                                                                                                                                                                                             
- [x] setuptools (27.2.0) - Latest: 36.3.0 [wheel]                                                                                                                                                                                                                                   
- [x] Twisted (17.1.0) - Latest: 17.5.0 [sdist]                                                                                                                                                                                                                                      
- [x] txaio (2.8.0) - Latest: 2.8.1 [wheel]                                                                                                                                                                                                                                          
- [x] vine (1.1.3) - Latest: 1.1.4 [wheel]                                                                                                                                                                                                                                           
- [x] whitenoise (3.2) - Latest: 3.3.0 [wheel] 

When a dependency is difficult or impossible to update, add a comment below describing the problem.

**Comment by brylie** [comment]
@mdwest, @tractaylor, @dborstelmann, @DCalliet, @pscheid2: would you mind re-tweeting the following tweet?

https://twitter.com/BrylieO/status/922493733542748160

Also, if anyone here is already interested in this task, feel free to update one or more of these dependencies. We can tackle this task a bit at a time :-)
