### ISSUE TITLE
Auto-lint CiviWiki JavaScript

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#46]
As part of our commitment to [clean](https://github.com/ryanmcdermott/clean-code-javascript) and maintainable code, we can lint our JavaScript. Linting will catch low-level details and encourage common coding conventions between CiviWiki developers.

# Goal
Enable automated linting on the CiviWiki project.

# Task
- [ ] Add ESLint metadata files to project root
- [ ] Inherit from existing ESLint style, such as [Airbnb ESLint rules](https://www.npmjs.com/package/eslint-config-airbnb)
- [ ] Override any of the Airbnb ESLint rules that we disagree with
- [ ] Run a project-wide lint, to see the extent of the problem
- [ ] Encourage CiviWiki developers to enable auto-linting in their IDE
- [ ] Enable auto-linting for CiviWiki GitHub pull requests

**Comment by tractaylor** [comment]
Here is a link to adding ESLint to many editors.  The same page has links on how to add github prehooks for projects.
https://eslint.org/docs/user-guide/integrations

**Comment by brylie** [comment]
@jl24 can we separate this PR from your frontend refactor PR? That way we can close this issue sooner.

**Comment by brylie** [comment]
@jl24 if we don't have a status for this, should I go ahead and move it to 0.3 milestone?

**Comment by JOO33** [comment]
Closing due to solution proposed by #827. The JS related issues will be no longer relevant.
