### ISSUE TITLE
Audit project test coverage

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#47]
As part of our commitment to code quality, we can measure test coverage in our project.

# Goal
Generate a test coverage report. Open an issue/discussion about improving test coverage.

# Task
- [x] install coverage.py as project dependency
- [x] generate test coverage report
- [x] share current code coverage with project leaders

**Comment by brylie** [comment]
The initial coverage report shows that we have 74% test coverage, despite having zero tests :smile: The 74% coverage comes by virtue of Django project and Python core being considered as 'under test'.

Here are the files we can prioritize among to write our initial tests:

```
Name                                                       Stmts   Miss  Cover
------------------------------------------------------------------------------
api/models/account.py                                        110     47    57%
api/models/activity.py                                        18      3    83%
api/models/civi.py                                           115     58    50%
api/models/invitation.py                                      37     20    46%
api/models/thread.py                                          57     16    72%
iviwiki/celery.py                                            10      2    80%
civiwiki/settings.py                                          76     26    66%
utils/__init__.py                                             16      9    44%
```

**Comment by tractaylor** [comment]
I would be happy to help with this.  I think writing tests are one of the best ways to learn about a new project.  I get all my new junior devs to create/write/update tests.  What is the test framework called that you want to use?  I will read up on it.

**Comment by brylie** [comment]
>  What is the test framework called that you want to use? Is it just the unittest module?

Follow the guidelines described in the [Testing in Django](https://docs.djangoproject.com/en/1.11/topics/testing/) documentation.

Create one issue for each file you will be testing, so we can break down the work into smaller chunks. In the issue, make a checklist of each unit or scenario you will be testing.

**Comment by delta-plus** [comment]
I got 30% coverage while testing my local clone. I think I'll write some tests for the prioritized files pretty soon, though.

**Comment by gorkemarslan** [comment]
@brylie, we have another pending issue related to improving test coverage. Could you close this one or that one? We can continue our test coverage discussions in one channel.
