### ISSUE TITLE
Design CiviWiki 'bill integration' API endpoints

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#50]
In order to retrieve data from Pro Publica and Open States APIs and send it to clients, we will need a 'wrapper' API. This way, we don't expose our CiviWiki API keys for the upstream services to CiviWiki users.

# Goal
Produce a design for the CiviWiki API endpoints, using a standard format. Get feedback on the API design.

# Task
- [ ] Design CiviWiki 'bill integration' API endpoints using OpenAPI Specification
- [ ] Get feedback about the proposed design from project stakeholders
- [ ] Make adjustments to the design based on stakeholder feedback
