### ISSUE TITLE
Update README for 0.1 release

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#61]
Our README is pretty much the first thing people see when visiting this repository. In preparation for the 0.1 release, we should have a well organized README.

# Goal
Have a user-friendly, informative README.

**Note**: the README, like the project, is a work-in-progress. We just want to spruce it up a bit for the 0.1 release.

# Task
- [x] Review current README, checking for
  - overall organization
  - 'out-of-place' text or phrases
  - grammar/spelling
  - missing information
- [x] Remove unneeded or duplicate text/sections
- [x] Change structure to fit the perspective of a new community member. E.g.
  - sections should be organized from general to specific
  - from low commitment to high commitment (e.g. trying a demo is easier than fixing a bug)
- [x] Review guidelines for helpful README files (resources section below)
- [x] Add sections that are recommended to include in a useful README

# Resources
- Open Leadership Training Series: [Writing a README.md ](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/)
- OpenSource Guide: Starting a project - [Writing a README](https://opensource.guide/starting-a-project/#writing-a-readme)
- 18F Open Source Style Guide: [Making READMEs readable](https://open-source-guide.18f.gov/making-readmes-readable/)
- StackOverflow: [How to write a good README](https://stackoverflow.com/questions/2304863/how-to-write-a-good-readme)
- PurpleBooth: [A template to make good README.md](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)
