### ISSUE TITLE
Create a CiviWiki Open Canvas

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#62]
Part of open project leadership is to have a clear idea of what we want to build, and to be able to quickly communicate that vision to stakeholders. The Open Canvas provides one such tool to quickly summarize a project. It lays out the parameters for building a Minimum Viable Project.

# Goal
Be able to communicate the high-level goals of CiviWiki to potential community members and stakeholders.

# Task
- [x] Complete the Open Leadership Academy [Open Canvas module](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/)
- [x] Apply the lessons from Open Leadership Academy to create an Open Canvas for the CiviWiki project
- [x] Involve other project stakeholders in the design, at the least asking for feedback
- [ ] Publish the OpenCiviWiki MVP Canvas in the project repository (`/docs/organization/`)

# Resources
- Open Leadership Academy: Opening your project -[Develop an open project strategy with open canvas](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/)

**Comment by brylie** [comment]
Closing, as completed by @mdwest
