### ISSUE TITLE
Thread View Frontend Issues

### ISSUE THREAD

**Issue by jl24** [CiviWiki/OpenCiviWiki#76]
The current thread view is clunky and confusing to interact with and improvements are necessary.

# Tasks
From #73 
1. Entering a Civi Thread
- [ ]  Delete the thread landing page and instead go to the main content page right away
- [ ]  Limit content to fit within the bounding box of the feed page
2. Civi Creation
- [ ]  When Problem/Cause/Solution Civi type selected, Display only Civies which can be linked to the type of Civi being created (if cause then link to problem, if solution then link to cause)
3. Civi Linking
- [ ]  Rather than typing the title of a Civi you want to link, allow the user to select a button to link a to other Civies, then click one one more civies from the list of relevant Civies displayed.
