### ISSUE TITLE
Consider using Matrix.org for CiviWiki related chat

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#84]
CiviWiki currently uses Slack for chat. However, there is an emerging, distributed, open source discussion network called Matrix that may be better suited to CiviWiki's values/mission.

# Goal
- Make it easy for CiviWiki community to gather and discuss the project
- Embrace federated/open source technologies to build the CiviWiki community
- Align with existing open-source and activist communities in the Matrix network

# Task
- [ ] Discuss the pros/cons of the Matrix network (as compared to Slack)
- [ ] Optionally, create test accounts to try out the features of Matrix network
- [ ] If we agree to create a Matrix CiviWiki channel, one of the core members of CiviWiki should create the channel, so they have admin rights
- [ ] All other contributers/community members can be invited to network
- [ ] Add 'Chat on Matrix' badge to README and perhaps CiviWiki.org

# Resources
- [Matrix.org homepage](https://matrix.org/) - official information about Matrix project
- [Riot.im](https://about.riot.im/) - open source web and mobile chat applications with support for Matrix protocol
- Example room on Matrix:
    - [Social.coop](https://riot.im/app/#/room/#SocialCoop:matrix.org) (username required)

**Comment by extremelypenguin** [comment]
What do you think about using Discord? Discord is an application very similar to Slack except all features are free including video sharing, screen sharing, and the like. https://discord.gg

**Comment by brylie** [comment]
We are currently using Matrix, as ot is open source and part of the movement to democratize online community platforms (a.k.a. the federated web). Please consider joining our room on Matrix:

https://matrix.to/#/#CiviWiki:matrix.org

If you would like to consolidate your communication channels into a single tool, you might also be interested in [Rambox](http://rambox.pro/) (also open source).

**Comment by brylie** [comment]
Here is a bit more [info about the federated/decentralized web and why it is important](https://ischoolonline.syr.edu/blog/what-is-the-decentralized-web/).
