### ISSUE TITLE
Complete most/all of OSS Checklist

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#87]
As part of our commitments to community and transparency, we can lay a solid foundation for the CiviWiki open-source project. To that end, we can use existing guidelines, such as the [OSS Checklist](https://github.com/scriptnull/oss-checklist).

# OSS Project Checklist

## Pre-checks
- [x] Able to explain your project in a tweet ?
- [x] Choose a name for the project
- [x] Check if domain name / App name is available ?
- [x] List and learn tools required for the project
- [x] Prepare mock-up and one page design document, if needed to explain to collaborators
- [x] List previous / similar implementations and learn from them
- [ ] Start a blog post to document the journey ( if time permits ) Mention idea + helpful resources.
- [ ] Ask if project could be solved in a modular way by dividing into sub-problems and creating a separate project for the sub-problems.

## Project Creation
- [x] Create a Repository in any of the Source Control Management sites
    - Github ( Free public repos )
    - Gitlab ( Free public and private repos + CI  + docker registry )
    - Bitbucket ( Free public and private repos )
- [x] Create a README.md (check below for more)
- [x] Create a LICENSE file (choose one before)
- [x] Create a CODE_OF_CONDUCT.md
- [x] Create a CONTRIBUTING.md
- [x] Create a .gitignore
- [x] Create [Gitter](https://gitter.im) chatroom (if needed)

## README.md Checklist
- [x] Title
- [x] Logo
- [x] Badges
- [x] Description
- [x] Prerequisite for using software ( if any )
- [ ] Install
- [ ] Example Usage
- [ ] Screenshots and GIFs
    - For command line apps, try [asciinema](https://asciinema.org/)
    - For mac GUI screenshots, use [Cmd+Shift+3] or [Cmd+Shift+4] or [Cmd+Shift+4,SpaceBar]
    - For mac GUI GIF creation, try [kap](https://getkap.co/)
    - For Ubuntu GUI Screenshots, use [Shift+PrintScr] or [Shutter](http://shutter-project.org/)
    - For Ubuntu GUI GIF creation, try [silentcast](https://github.com/colinkeenan/silentcast)
- [ ] Contributors
- [x] Backers and Sponsors
- [x] Attributions ( mention 3rd party libs used etc. )
- [ ] Security
    - [ ] Post maintainer's PGP fingerprint for reporting security vulnerabilities
    - [ ] Share [keybase](https://keybase.io/) profile for making the reporting process easier.

## Coding Phase
- [x] Install required developer tools
    - [ ] Compiler
    - [x] Linter
    - [x] Formatter
    - [ ] Build Tool
    - [ ] Other
- [x] Organise files and folders that will help readers to find code easily
- [ ] Basic code complete
- [ ] Write tests and keep watch on code coverage
- [ ] Setup CI
- [x] Host the documentation of the code somewhere if the project is a software library 
- [x] Use Github issues ( or other tools ) for tracking backlogs
- [x] Encourage OSS culture by having labels like "help wanted" "easy-to-contribute" etc.
- [ ] Contribute to other OSS projects on which the current project is dependent on ( if possible )
    - File bug reports
    - Improve docs
    - Suggest feature
    - Learn by reading code

## Release Phase
- [ ] Package software in CI or manually in local
- [ ] Publish in registries (npm, docker hub etc.) or markets (Android store, App Store etc.)
- [ ] Create the release version, description, link for downloading the release etc. in release page ( example: Github release page)

## Post-release
- [ ] Publish the blog post
- [ ] [Tweet](https://twitter.com/)
- [ ] [Hackernews](https://news.ycombinator.com/)
- [ ] [Product Hunt](http://producthunt.com/)
- [ ] Send PR to `awesome-*` github repository
- [ ] [Reddit](https://www.reddit.com)
- [ ] [Hashnode](https://hashnode.com/)
- [ ] [Linkedin](https://www.linkedin.com/)
- [ ] Edit Wikipedia pages (if related)
- [ ] Prepare slides and give talks (if possible)

**Comment by pscheid2** [comment]
'Ask if project could be solved in a modular way by dividing into sub-problems and creating a separate project for the sub-problems.'

Hmm, I don't think I can think of a way to split the functionality of this platform into separate pieces efficiently.

The pieces I see are:
-The typical user entering issue/cause/solution civis and commenting on civis expressing their opinion
-The legislator/representative adding bills or policy changes they want feedback on

But I think separating those pieces would cause communication issues which is what we're trying to promote

**Comment by pscheid2** [comment]
@mdwest do you have a concise description of civiwiki that can fit in a tweet?

**Comment by pscheid2** [comment]
@brylie Do we think we should be putting the Contributors and Sponsers in the Contributing.md or Readme.md?

Is it enough that the information is on the github or the website?

**Comment by brylie** [comment]
Probably in the README, since it is more prominent and we want to give credit/thanks.

**Comment by pscheid2** [comment]
Completing this issue has very large scope since it includes things like "setting up CI" and being "basic code complete". We have separate issues for these tasks, so I'm thinking we should close this issue since we have other issues tracking the work from this checklist that we want to focus on.

I think it's a good idea to review this checklist when we finish milestone 2.0, but most likely broken into smaller issues.
