### ISSUE TITLE
Move Account and Profile related code to accounts app

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#926]
We still have some code in the `api` directory that is related to user accounts/profiles. Move all account/profile code to the `accounts` app and refactor as needed.

Relatedly, rename the `Account` model to `Profile`.

## Task
Below are the overarching steps involved in completing this issue. Some steps are optional but might help us achieve cleaner and more maintainable code.

- [ ] Move all code indicated below to the `accounts` app
- [ ] refactor related code to reference the new location
- [ ] (optional) remove redundant code, if possible
- [ ] (optional) clean-up existing code if there are more conventional ways of doing things

## Related code
All code below should be moved to the `accounts` app.

- [ ] Move `Account` model to the `accounts.models` and rename the model to `Profile`:
https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/models/account.py#L1-L3

- [ ] Move Accounts views to the `accounts` app:
- https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/views/account.py

- [ ] Move account/password related forms to `accounts` app:
- https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/forms.py

- [ ] Move User serializer to `accounts` app
https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/read.py#L8-L22

- [ ] User card serializer
https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/read.py#L25-L40

- [ ] Profile serializer
- https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/read.py#L43-L96

- [ ] Account-related read-only serializers
https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/serializers.py#L10-L116

- [ ] Account and profile related URLs
https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/urls.py#L10
https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/urls.py#L19-L21
https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/urls.py#L38-L49

- [ ] user-related utility function
https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/utils.py#L12-L22

- [ ] user/profile "write" endpoints
https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/write.py#L299-L583

**Comment by brylie** [comment]
@shashankks0987 would you be interested in taking this issue?

**Comment by shashankks0987** [comment]
@brylie  Yes I'd be happy to

**Comment by brylie** [comment]
Thanks! I've assigned you.

I'll try and add a list of related code that I can find.

When working, try to figure out which code isn't needed anymore and remove it. If there is a more conventional way to do things with Django, replace any custom code with the conventional method

**Comment by NoriakiMawatari** [comment]
Helloo @brylie, I'm very interested in contributing and would love to help with this issue or another good first issue! Please let me know what can I do for the team.

**Comment by RiddhiAthreya** [comment]
hey @brylie I'm new to contributing to open source and would love to contribute here! Let me know if there are issues I can contribute to!

**Comment by brylie** [comment]
Thank you for your offer @RiddhiAthreya and @NoriakiMawatari. Since @shashankks0987 is currently working on this task, we would need to see how you might assist them.

@shashankks0987 is there any way that @RiddhiAthreya and @NoriakiMawatari can assist you with this task?

**Comment by shashankks0987** [comment]
I'm currently working on issue #849 as that was of higher priority. I thought I'll get back to this after that. If they are open to take it, you can assign them too and I can later continue from where they left off

**Comment by RiddhiAthreya** [comment]
@brylie can I be assigned this issue?

**Comment by brylie** [comment]
@RiddhiAthreya sure thing. You're assigned :-) 

If you wouldn't mind, please check in with @shashankks0987 periodically as they are stewarding this task along with a couple of related tasks

**Comment by sandipan898** [comment]
Is this issue still open to fix, or someone have already fixed it?

**Comment by Adyyousf** [comment]
can i fix this issue?

**Comment by brylie** [comment]
@skattel49 still has a pull request in prorgress here and @wassafshahzad is working on related code. Let's try to avoid too many collisions in this area of the project. 

@wassafshahzad, is there any way that @sandipan898 and @Adyyousf may assist you?

**Comment by ghost** [comment]
@brylie I am unable to find the account.py file . I am looking for my first contribution.

**Comment by brylie** [comment]
Ah, this task is basically complete.

**Comment by brylie** [comment]
@sonu03 would you be interested in helping with https://github.com/CiviWiki/OpenCiviWiki/issues/231?

**Comment by gorkemarslan** [comment]
@brylie is it possible to reopen this issue and assign me to it? Now I am writing unit testing for `accounts` app (issue #952) and some maintenance is needed to improve `models.py` file (not the models but codes in the file). While I am testing, I also want to fix some omitted problems because of moving other models to the `accounts/models.py`. For example, there are some code repetitions, etc. 
Otherwise, should I create a new issue?

**Comment by brylie** [comment]
> Otherwise, should I create a new issue?

Yes, for the sake of clarity, please create a new issue outlining the planned changes. I'll make sure you are assigned to the new issue.

**Comment by ghost** [comment]
@brylie yes, I will check out issue #231
